FROM ubuntu:16.04
RUN apt-get update && apt-get install -yqq unzip curl wget libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1
RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
COPY . /WatchRuMonitoring_bot
WORKDIR /WatchRuMonitoring_bot
RUN apt update && apt install -y python3 python3-pip libsqlcipher-dev
RUN pip3 install -r requirements.txt
CMD ["python3", "WatchRuForumScrapper.py", "--docker", "True"]