FROM ubuntu:16.04
COPY . /WatchRuMonitoring_bot
WORKDIR /WatchRuMonitoring_bot
RUN apt update && apt install -y python3 python3-pip libsqlcipher-dev
RUN pip3 install -r requirements.txt
CMD ["python3", "WatchRuForumBot.py"]